# Docker Compose file to orchestrate WordPress, MySQL, a Next.js dashboard, and Nginx reverse proxy.

version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./home:/var/www/html # Mount your 'home' folder for themes/plugins
    ports:
      - "8081:80" # Expose WordPress on port 8080 for direct access if needed
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  dashboard:
    build:
      context: ./dashboard/frontend
      args:
        FLASK_API_URL: ${FLASK_API_URL_DOCKER}
        NEXT_PUBLIC_FLASK_API_URL: ${NEXT_PUBLIC_FLASK_API_URL}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always
    environment:
      FLASK_API_URL: ${FLASK_API_URL_DOCKER}
      NEXT_PUBLIC_FLASK_API_URL: ${NEXT_PUBLIC_FLASK_API_URL}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000" # Dashboard available at localhost:3000

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
      - dashboard
    restart: always

volumes:
  db_data: